server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3308/cloud_order?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mo
    driver-class-name: com.mysql.cj.jdbc.Driver   #mysql8.0版本以上指定
mybatis:
  type-aliases-package: com.mo.moloom.pojo
  configuration:
    map-underscore-to-camel-case: true

#log4j2 配置
logging:
  config: classpath:log4j-setting.xml