server:
  port: 8080
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8848           #nacos服务地址
      discovery:
        cluster-name: HZ            #集群名称
  datasource:
    url: jdbc:mysql://localhost:3308/cloud_order?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mo
    driver-class-name: com.mysql.cj.jdbc.Driver   #mysql8.0版本以上指定
mybatis:
  type-aliases-package: com.mo.moloom.pojo
  configuration:
    map-underscore-to-camel-case: true

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

feign:
  client:
    config:
      user-service: # 针对某个微服务的配置
        loggerLevel: BASIC #  日志级别


#log4j2 配置
logging:
  config: classpath:log4j-setting.xml
  level:
    com.mo.moloom: debug