server:
  port: 10000
spring:
  application:
    name: eureka-server    #这是Eureka上的该服务名

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，不需要去检索服务
    fetch-registry: false
    service-url:        #Eureka地址信息
      defaultZone: http://localhost:10000/eureka

ribbon:
  eager-load:
    enabled: true       #开启饥饿加载
    clients: user-service         #指定对user-service这个服务饥饿加载

#log4j2 配置
logging:
  config: classpath:log4j-setting.xml